# Generated by Django 5.1.6 on 2025-02-17 05:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='expiry',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='packages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='packageimage/'),
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
