# Generated by Django 5.1.6 on 2025-02-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_packages_expiry_alter_packages_image_delete_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
