# Generated by Django 5.1.6 on 2025-02-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_packages_is_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
