# Generated by Django 5.1.6 on 2025-02-24 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_packages_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='is_paid',
        ),
    ]
