# Generated by Django 5.1.6 on 2025-02-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_packages_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('vendor', 'Vendor')], default='user', max_length=100),
        ),
    ]
