# Generated by Django 5.1.6 on 2025-02-28 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_vendor_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='company_address',
            new_name='address',
        ),
    ]
